name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: python -m pip install poetry
    - name: Install dependencies
      run: |
        poetry add pytest pytest-cov flake8 pydocstyle bandit
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test, check coverage
      run: poetry run pytest ./test/ --cov=src --cov-branch --cov-fail-under=60
    - name: Security check with bandit
      run: poetry run bandit ./src/
    - name: Documentation check with pydocstyle
      run: pydocstyle ./
