name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: python -m pip install poetry
    - name: Install dependencies
      run: |
        poetry add pytest pytest-cov flake8 radon pydocstyle bandit
        poetry install
    - name: Lint with flake8
      run: poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Cyclomatic Complexity check with radon
      run: |
        output=$(poetry run radon cc --min C ./src/ --exclude "test_*.py" --json)
        
        # Check if any results exist
        if [ "$output" != "{}" ]; then
          echo "::error::Found complex code (rank C or worse)"
          echo "$output"
          exit 1
        fi
    - name: Security check with bandit
      run: poetry run bandit ./src/
    - name: Unit tests, coverage check
      env:
        BOT_TOKEN: "1234567890:TEST_TOKEN_ABC-DEF1234ghIkl"
        CHANNEL_ID: "-1001234567890"
        IMGFLIP_USER: "test_user"
        IMGFLIP_PASS: "test_pass"
      run: poetry run pytest ./tests/unit/ --cov=src --cov-branch --cov-fail-under=60
    - name: Documentation check with pydocstyle
      run: pydocstyle ./
